const scene5Data = [
    { id: 'prologue_5_1', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, type: 'narrator', text: '夜晚。艾登家。窗外夜色安静。桌上摆着晚饭。', next: 'prologue_5_2' },
    { id: 'prologue_5_2', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾琳', text: '所以我宣布——今天晚上不准你乱跑。', next: 'prologue_5_3' },
    { id: 'prologue_5_3', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾登', text: '为什么？', next: 'prologue_5_4' },
    { id: 'prologue_5_4', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾琳', text: '因为你才刚醒。', next: 'prologue_5_5' },
    { id: 'prologue_5_5', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾登', text: '我只是昏迷，不是残废。', next: 'prologue_5_6' },
    { id: 'prologue_5_6', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾琳', text: '那也不行。今天必须听我的。', next: 'prologue_5_7' },
    { id: 'prologue_5_7', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾登', text: '你今天是不是有点太强势了。', next: 'prologue_5_8' },
    { id: 'prologue_5_8', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾琳', text: '有吗？我觉得还好。', next: 'prologue_5_9' },
    { id: 'prologue_5_9', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾登', text: '完全没有说服力。', next: 'prologue_5_10' },
    { id: 'prologue_5_10', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, type: 'narrator', text: '艾琳轻轻笑起来。屋内很温暖，灯火摇曳，一切都和平常一样。', next: 'prologue_5_11' },
    { id: 'prologue_5_11', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾琳', text: '对了，明天陪我去山上吧。花应该开了，我想去看看。', next: 'prologue_5_12' },
    { id: 'prologue_5_12', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾登', text: '好。', next: 'prologue_5_13' },
    { id: 'prologue_5_13', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾琳', text: '真的？不准反悔。', next: 'prologue_5_14' },
    { id: 'prologue_5_14', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾登', text: '知道了。', next: 'prologue_5_15' },
    { id: 'prologue_5_15', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, type: 'effect', effect: 'pause', text: '', next: 'prologue_5_16' },
    { id: 'prologue_5_16', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, type: 'narrator', text: '艾琳托着下巴看着艾登。', next: 'prologue_5_17' },
    { id: 'prologue_5_17', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾登', text: '……你一直看着我干嘛？', next: 'prologue_5_18' },
    { id: 'prologue_5_18', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾琳', text: '确认一下。', next: 'prologue_5_19' },
    { id: 'prologue_5_19', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾登', text: '确认什么？', next: 'prologue_5_20' },
    { id: 'prologue_5_20', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾琳', text: '你是不是真的醒了。', next: 'prologue_5_21' },
    { id: 'prologue_5_21', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾登', text: '……那确认结果呢？', next: 'prologue_5_22' },
    { id: 'prologue_5_22', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, name: '艾琳', text: '嗯。是真的。', next: 'prologue_5_23' },
    { id: 'prologue_5_23', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, type: 'effect', effect: 'pause', text: '', next: 'prologue_5_24' },
    { id: 'prologue_5_24', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, type: 'narrator', text: '忽然。远处传来一声闷响。咚——', next: 'prologue_5_25' },
    { id: 'prologue_5_25', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_happy' }, type: 'effect', effect: 'pause', text: '', next: 'prologue_5_26' },
    { id: 'prologue_5_26', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '咚——咚——像是很远的地方，传来沉重撞击声。地面甚至轻微震动了一下。', next: 'prologue_5_27' },
    { id: 'prologue_5_27', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾登', text: '什么声音？', next: 'prologue_5_28' },
    { id: 'prologue_5_28', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾琳', text: '不知道……', next: 'prologue_5_29' },
    { id: 'prologue_5_29', scene: '序章 Scene 5：夜袭', background: 'erin_room', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '第三声巨响。轰——！！', next: 'prologue_5_30' },
    { id: 'prologue_5_30', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '窗外亮起刺眼火光。村民的尖叫声撕裂夜空。', next: 'prologue_5_31' },
    { id: 'prologue_5_31', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾登', text: '？！', next: 'prologue_5_32' },
    { id: 'prologue_5_32', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾琳', text: '发生什么了？！', next: 'prologue_5_33' },
    { id: 'prologue_5_33', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '艾登猛地起身冲到窗边，下一秒瞳孔骤缩。', next: 'prologue_5_34' },
    { id: 'prologue_5_34', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '火焰冲天而起，房屋坍塌，巨大的黑影站在村口，扭曲而狰狞。', next: 'prologue_5_35' },
    { id: 'prologue_5_35', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾登', text: '那是……', next: 'prologue_5_36' },
    { id: 'prologue_5_36', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾琳', text: '魔物……？', next: 'prologue_5_37' },
    { id: 'prologue_5_37', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '轰鸣、房屋坍塌、村民哭喊……', next: 'prologue_5_38' },
    { id: 'prologue_5_38', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾登', text: '不对劲。为什么会有魔物出现在这里？！', next: 'prologue_5_39' },
    { id: 'prologue_5_39', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾琳', text: 'XX哥哥……', next: 'prologue_5_40' },
    { id: 'prologue_5_40', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '艾琳声音在发抖。', next: 'prologue_5_41' },
    { id: 'prologue_5_41', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾登', text: '艾琳，待在这里。', next: 'prologue_5_42' },
    { id: 'prologue_5_42', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾琳', text: '不行！外面太危险了！', next: 'prologue_5_43' },
    { id: 'prologue_5_43', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾登', text: '我得去救人！', next: 'prologue_5_44' },
    { id: 'prologue_5_44', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '轰！！一只魔物撞碎旁边房屋，碎石飞溅，近得可怕。', next: 'prologue_5_45' },
    { id: 'prologue_5_45', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾琳', text: '呀——！', next: 'prologue_5_46' },
    { id: 'prologue_5_46', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '艾登一把抱住艾琳扑倒，碎石砸落，烟尘四起。', next: 'prologue_5_47' },
    { id: 'prologue_5_47', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾登', text: '咳……', next: 'prologue_5_48' },
    { id: 'prologue_5_48', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾琳', text: 'XX哥哥！', next: 'prologue_5_49' },
    { id: 'prologue_5_49', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '低沉嘶吼声，很近，非常近。烟尘中亮起猩红双眼。', next: 'prologue_5_50' },
    { id: 'prologue_5_50', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾琳', text: '它过来了……', next: 'prologue_5_51' },
    { id: 'prologue_5_51', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '魔物逼近，脚步沉重，地面震动。', next: 'prologue_5_52' },
    { id: 'prologue_5_52', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'thought', name: '艾登', text: '该死。怎么办？怎么办——', next: 'prologue_5_choice_1' },
    { id: 'prologue_5_choice_1', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, choices: [{ text: '逃', next: 'prologue_5_53' }, { text: '战斗', next: 'prologue_5_53' }] },
    { id: 'prologue_5_53', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '就在瞬间——一道银光闪过。噗嗤。鲜血飞溅。', next: 'prologue_5_54' },
    { id: 'prologue_5_54', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '魔物头颅落地。', next: 'prologue_5_55' },
    { id: 'prologue_5_55', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'selena_default', right: 'erin_worry' }, name: '???', text: '退后。', next: 'prologue_5_56' },
    { id: 'prologue_5_56', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'selena_default', right: 'erin_worry' }, type: 'narrator', text: '烟尘散去。银白长发在火光中轻轻扬起，手中长剑滴着血，冰蓝色双瞳冷静得可怕。', next: 'prologue_5_57' },
    { id: 'prologue_5_57', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'selena_default', right: 'erin_worry' }, name: '塞琳娜', text: '带着她离开这里。现在。', next: 'prologue_5_58' },
    { id: 'prologue_5_58', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'selena_default', right: 'erin_worry' }, name: '艾登', text: '你是……', next: 'prologue_5_59' },
    { id: 'prologue_5_59', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'selena_default', right: 'erin_worry' }, name: '塞琳娜', text: '王国执行者。塞琳娜。', next: 'prologue_5_60' },
    { id: 'prologue_5_60', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'selena_default', right: 'erin_worry' }, type: 'narrator', text: '更多魔物出现。', next: 'prologue_5_61' },
    { id: 'prologue_5_61', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'selena_default', right: 'erin_worry' }, name: '塞琳娜', text: '别发呆。数量越来越多了。快走。', next: 'prologue_5_62' },
    { id: 'prologue_5_62', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'selena_default', right: 'erin_worry' }, name: '艾登', text: '艾琳，走！', next: 'prologue_5_63' },
    { id: 'prologue_5_63', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '艾登抓住艾琳的手，两人开始逃跑。塞琳娜断后。村庄彻底陷入火海，四处都是尖叫，到处是血与火。', next: 'prologue_5_64' },
    { id: 'prologue_5_64', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾琳', text: '为什么会变成这样……为什么……', next: 'prologue_5_65' },
    { id: 'prologue_5_65', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾登', text: '别怕！我在！', next: 'prologue_5_66' },
    { id: 'prologue_5_66', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '两人冲向村口，眼看就要逃出去——忽然，世界安静了。', next: 'prologue_5_67' },
    { id: 'prologue_5_67', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'effect', effect: 'timeStop', text: '', next: 'prologue_5_68' },
    { id: 'prologue_5_68', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, type: 'narrator', text: '所有声音消失。火焰停止摇曳。碎石悬浮在半空。整个世界像被冻结。', next: 'prologue_5_69' },
    { id: 'prologue_5_69', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_worry' }, name: '艾登', text: '……什么？', next: 'prologue_5_70' },
    { id: 'prologue_5_70', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_fear' }, type: 'narrator', text: '艾琳僵住了。瞳孔剧烈收缩，脸色瞬间惨白，像是看见了什么极恐怖的东西。', next: 'prologue_5_71' },
    { id: 'prologue_5_71', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾登', text: '艾琳？', next: 'prologue_5_72' },
    { id: 'prologue_5_72', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾琳', text: '不对。不对……', next: 'prologue_5_73' },
    { id: 'prologue_5_73', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_fear' }, type: 'narrator', text: '她开始发抖。', next: 'prologue_5_74' },
    { id: 'prologue_5_74', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾登', text: '怎么了？！', next: 'prologue_5_75' },
    { id: 'prologue_5_75', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾琳', text: '它来了。', next: 'prologue_5_76' },
    { id: 'prologue_5_76', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾登', text: '谁？', next: 'prologue_5_77' },
    { id: 'prologue_5_77', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾琳', text: '它又来了——！', next: 'prologue_5_78' },
    { id: 'prologue_5_78', scene: '序章 Scene 5：夜袭', background: 'village_fire', characters: { left: 'aiden_default', right: 'erin_fear' }, type: 'effect', effect: 'crack', text: '', next: 'prologue_5_79' },
    { id: 'prologue_5_79', scene: '序章 Scene 5：夜袭', background: 'crack', characters: { left: 'aiden_default', right: 'erin_fear' }, type: 'narrator', text: '空间开始扭曲。艾琳身后，空气裂开，像镜面破碎，露出漆黑深渊。', next: 'prologue_5_80' },
    { id: 'prologue_5_80', scene: '序章 Scene 5：夜袭', background: 'crack', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾登', text: '？！艾琳！！', next: 'prologue_5_81' },
    { id: 'prologue_5_81', scene: '序章 Scene 5：夜袭', background: 'crack', characters: { left: 'aiden_default', right: 'erin_fear' }, type: 'narrator', text: '裂缝爆发巨大吸力，艾琳被猛地拖向后方。', next: 'prologue_5_82' },
    { id: 'prologue_5_82', scene: '序章 Scene 5：夜袭', background: 'crack', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾琳', text: '啊——！！', next: 'prologue_5_83' },
    { id: 'prologue_5_83', scene: '序章 Scene 5：夜袭', background: 'crack', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾登', text: '抓住我！！', next: 'prologue_5_84' },
    { id: 'prologue_5_84', scene: '序章 Scene 5：夜袭', background: 'crack', characters: { left: 'aiden_default', right: 'erin_fear' }, type: 'narrator', text: '艾登死死抓住她。', next: 'prologue_5_85' },
    { id: 'prologue_5_85', scene: '序章 Scene 5：夜袭', background: 'crack', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾琳', text: 'XX哥哥！！', next: 'prologue_5_86' },
    { id: 'prologue_5_86', scene: '序章 Scene 5：夜袭', background: 'crack', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾登', text: '别松手！！', next: 'prologue_5_87' },
    { id: 'prologue_5_87', scene: '序章 Scene 5：夜袭', background: 'crack', characters: { left: 'aiden_default', right: 'erin_fear' }, type: 'narrator', text: '空间崩裂声越来越响。咔嚓。咔嚓。像整个世界在碎裂。', next: 'prologue_5_88' },
    { id: 'prologue_5_88', scene: '序章 Scene 5：夜袭', background: 'crack', characters: { left: 'aiden_default', right: 'erin_fear' }, type: 'narrator', text: '艾琳看着艾登，眼中的恐惧忽然变了，像是想起了什么，像是终于明白了什么。', next: 'prologue_5_89' },
    { id: 'prologue_5_89', scene: '序章 Scene 5：夜袭', background: 'crack', characters: { left: 'aiden_default', right: 'erin_fear' }, name: '艾琳', text: '爱——！！', next: 'prologue_5_90' },
    { id: 'prologue_5_90', scene: '序章 Scene 5：夜袭', background: 'crack', characters: {}, type: 'effect', effect: 'blackScreen', text: '', next: 'prologue_5_91' },
    { id: 'prologue_5_91', scene: '序章 Scene 5：夜袭', background: 'black', characters: {}, type: 'narrator', text: '下一秒，艾琳被黑暗吞没。', next: 'prologue_5_92' },
    { id: 'prologue_5_92', scene: '序章 Scene 5：夜袭', background: 'black', characters: {}, name: '艾登', text: '艾琳——！！！', next: 'prologue_5_93' },
    { id: 'prologue_5_93', scene: '序章 Scene 5：夜袭', background: 'black', characters: {}, type: 'effect', effect: 'pause', text: '', next: 'prologue_6_1' }
];