const scene6Data = [
    { id: 'prologue_6_1', scene: '序章 Scene 6：废墟', background: 'black', characters: {}, type: 'narrator', text: '耳边全是杂音。火焰燃烧声、房屋坍塌声、哭喊声，还有自己的喘息声。', next: 'prologue_6_2' },
    { id: 'prologue_6_2', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, type: 'narrator', text: '画面缓缓亮起。燃烧的村庄，浓烟弥漫，夜色被火焰染红。', next: 'prologue_6_3' },
    { id: 'prologue_6_3', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, type: 'narrator', text: '艾登跪在地上，双眼失焦，手还保持着抓握的姿势，像是想抓住什么，却什么都没有。', next: 'prologue_6_4' },
    { id: 'prologue_6_4', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, name: '艾登', text: '艾琳……', next: 'prologue_6_5' },
    { id: 'prologue_6_5', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '站起来。', next: 'prologue_6_6' },
    { id: 'prologue_6_6', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '……', next: 'prologue_6_7' },
    { id: 'prologue_6_7', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '她已经不在这里了。', next: 'prologue_6_8' },
    { id: 'prologue_6_8', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '……', next: 'prologue_6_9' },
    { id: 'prologue_6_9', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, type: 'narrator', text: '艾登缓缓抬头。塞琳娜站在火光中，长剑上还沾着血，冰蓝色双瞳依旧冷静，冷静得近乎残酷。', next: 'prologue_6_10' },
    { id: 'prologue_6_10', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '你说什么？', next: 'prologue_6_11' },
    { id: 'prologue_6_11', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '我说，她已经不在这里了。', next: 'prologue_6_12' },
    { id: 'prologue_6_12', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '不可能。她刚刚还在这里。她刚刚还——', next: 'prologue_6_13' },
    { id: 'prologue_6_13', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '……她去哪了？', next: 'prologue_6_14' },
    { id: 'prologue_6_14', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '不知道。', next: 'prologue_6_15' },
    { id: 'prologue_6_15', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '不知道？', next: 'prologue_6_16' },
    { id: 'prologue_6_16', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '你不是王国执行者吗？！你不是来救人的吗？！那你告诉我——艾琳去哪了？！', next: 'prologue_6_17' },
    { id: 'prologue_6_17', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, type: 'narrator', text: '短暂沉默。火焰在周围燃烧，映得塞琳娜侧脸忽明忽暗。', next: 'prologue_6_18' },
    { id: 'prologue_6_18', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '你刚才看见了什么？', next: 'prologue_6_19' },
    { id: 'prologue_6_19', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '什么？', next: 'prologue_6_20' },
    { id: 'prologue_6_20', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '回答我。她消失前，你看见了什么？', next: 'prologue_6_21' },
    { id: 'prologue_6_21', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '世界……停住了。火焰不动了，所有声音都消失了。', next: 'prologue_6_22' },
    { id: 'prologue_6_22', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '然后……她身后裂开了，像黑洞一样，然后她就——', next: 'prologue_6_23' },
    { id: 'prologue_6_23', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, type: 'narrator', text: '艾登说不下去了。', next: 'prologue_6_24' },
    { id: 'prologue_6_24', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '果然。', next: 'prologue_6_25' },
    { id: 'prologue_6_25', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '什么果然？', next: 'prologue_6_26' },
    { id: 'prologue_6_26', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '边境异常已经扩散到这里了。', next: 'prologue_6_27' },
    { id: 'prologue_6_27', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '边境异常？', next: 'prologue_6_28' },
    { id: 'prologue_6_28', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '最近边境出现了很多无法解释的现象。魔物暴动、空间扭曲、还有……失踪。', next: 'prologue_6_29' },
    { id: 'prologue_6_29', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '你是说……艾琳还活着？', next: 'prologue_6_30' },
    { id: 'prologue_6_30', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '我不知道。但如果她被卷进了异常区域……就还有找到她的可能。', next: 'prologue_6_31' },
    { id: 'prologue_6_31', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, type: 'narrator', text: '原本空洞的眼神忽然有了一丝光。', next: 'prologue_6_32' },
    { id: 'prologue_6_32', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '我要去。', next: 'prologue_6_33' },
    { id: 'prologue_6_33', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '什么？', next: 'prologue_6_34' },
    { id: 'prologue_6_34', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '我要去找她。', next: 'prologue_6_35' },
    { id: 'prologue_6_35', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '你知道自己在说什么吗？那不是你能接触的领域。', next: 'prologue_6_36' },
    { id: 'prologue_6_36', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '那又怎样？我要去找她。不管她在哪，我都要把她带回来。', next: 'prologue_6_37' },
    { id: 'prologue_6_37', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, type: 'narrator', text: '塞琳娜看着艾登，长久沉默。', next: 'prologue_6_38' },
    { id: 'prologue_6_38', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '你会死。', next: 'prologue_6_39' },
    { id: 'prologue_6_39', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '那也无所谓。', next: 'prologue_6_40' },
    { id: 'prologue_6_40', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, type: 'narrator', text: '风吹过，火焰摇曳。塞琳娜看着眼前的少年，眼中第一次出现细微波动。', next: 'prologue_6_41' },
    { id: 'prologue_6_41', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '塞琳娜', text: '明天。王国征军会经过这里。如果你还没改变主意，就跟上。', next: 'prologue_6_42' },
    { id: 'prologue_6_42', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, type: 'narrator', text: '塞琳娜转身离开。', next: 'prologue_6_43' },
    { id: 'prologue_6_43', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, name: '艾登', text: '等等！', next: 'prologue_6_44' },
    { id: 'prologue_6_44', scene: '序章 Scene 6：废墟', background: 'ruins', characters: { left: 'aiden_default', right: 'selena_default' }, type: 'narrator', text: '塞琳娜停住，没有回头。', next: 'prologue_6_45' },
    { id: 'prologue_6_45', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, name: '艾登', text: '我一定会找到她的。', next: 'prologue_6_46' },
    { id: 'prologue_6_46', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, name: '塞琳娜', text: '希望如此。', next: 'prologue_6_47' },
    { id: 'prologue_6_47', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, type: 'narrator', text: '塞琳娜离去，身影逐渐消失在火光里。', next: 'prologue_6_48' },
    { id: 'prologue_6_48', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, type: 'narrator', text: '艾登独自站在废墟中央。夜风吹过，浓烟弥漫，整个村庄都毁了，一切都变得陌生。', next: 'prologue_6_49' },
    { id: 'prologue_6_49', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, type: 'thought', name: '艾登', text: '明明几个小时前，一切都还很正常。艾琳还在自己身边笑着，拉着自己的袖子，说着明天的计划。', next: 'prologue_6_50' },
    { id: 'prologue_6_50', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, type: 'thought', name: '艾琳', text: '明天也陪我。', next: 'prologue_6_51' },
    { id: 'prologue_6_51', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, type: 'thought', name: '艾琳', text: '不要丢下我。', next: 'prologue_6_52' },
    { id: 'prologue_6_52', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, type: 'thought', name: '艾琳', text: '只要XX哥哥在，我就什么都不怕。', next: 'prologue_6_53' },
    { id: 'prologue_6_53', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, type: 'effect', effect: 'pause', text: '', next: 'prologue_6_54' },
    { id: 'prologue_6_54', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, name: '艾登', text: '等我。', next: 'prologue_6_55' },
    { id: 'prologue_6_55', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, name: '艾登', text: '艾琳。', next: 'prologue_6_56' },
    { id: 'prologue_6_56', scene: '序章 Scene 6：废墟', background: 'ruins', characters: {}, name: '艾登', text: '我一定会找到你。', next: 'prologue_end' }
];